server:
  port: 18800
  ssl:
    enabled: true
    key-store-type: JKS
    key-store: classpath:ca/ahzx.site.jks
    key-password: 6fb6xbdn9249
    key-alias: ahzx.site
spring:
  application:
    name: chazuo
  #mysql连接配置
  datasource:
    url: jdbc:mysql://129.211.4.96:12098/chazuo
    username: dcm
    password: N8xvZ2Q4kP5mT7wL
mybatis:
  mapper-locations:
    classpath:mapper/*xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    root: debug
    site.ahzx: debug
    org.springframework.jdbc.support.JdbcTransactionManager: debug

wx:
  app-id: wxd224c8ebd820134f
  app-secret: 00312b240ea42800e597079f0c42f71c


jwt:
  secret: yuzhouwudichaojidashuaibihuxuefengshiye # 请替换为实际的JWT密钥
  expiration-hours: 86400 # token有效期(秒)
  token-header: Authorization
  token-prefix: "Bearer "

