server:
  port: 18800
  ssl:
    enabled: true
    key-store-type: JKS
    key-store: classpath:ca/ahzx.site.jks
    key-password: 6fb6xbdn9249
    key-alias: ahzx.site
spring:
  application:
    name: chazuo
  #mysql连接配置
  datasource:
    url: jdbc:mysql://129.211.4.96:12098/chazuo
    username: dcm
    password: N8xvZ2Q4kP5mT7wL
mybatis:
  mapper-locations:
    classpath:mapper/*xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    site.ahzx: debug
    org.springframework.jdbc.support.JdbcTransactionManager: info

wx:
  app-id: wxd224c8ebd820134f
  app-secret: 00312b240ea42800e597079f0c42f71c

sms:
  app-key: 204893391
  app-secret: sKksgWZcbesUF75V4E9NRJw6OhK6NTGv
  app-code: 792dbe5007444befae8aef51b8c6c5b4
  template_id: CST_ptdie100
  host: https://dfsns.market.alicloudapi.com
  path: /data/send_sms
  methos: POST


jwt:
  secret: yuzhouwudichaojidashuaibihuxuefengshiye # 请替换为实际的JWT密钥
  expiration-hours: 86400 # token有效期(秒)
  token-header: Authorization
  token-prefix: "Bearer "

alipay:
  app-id: 9021000140623471
  app-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCQpuLhEYrpuaAKHF5D4EZ2ObgVqy5PFaBCsH8Y8ep5JF2MDHn/rRG6YXaw23WncnUn/6yFlwdpwRAHojWUlK33XxLEFR9V4q5QfDh2URPp6JQEp8fuWroncUziHnPpV/heFN02NWcwr1j729NghwOuYeJAWg4WxJH5521WRyBPEPN/WErthFFUojLH3mkaJ19n7bR4ARnNLQ0AP7cYfh0x6apNwzPGj7GbVgaxW0mQMXl6PrvZ4twoBhZwaUQFAfhWqQtWV1VwLt+Of0n7SbuKj6ohLb8O50VBlYf+nTC2aSBtv3G1atigGUciAqiU19yH6VGrKJJ7zzDCmSwPxJYxAgMBAAECggEAPJSYGjiVm/Mw0ms1E2o/OE5OCU0q1NYyyxtN722JjHitcPTctzaNYShmZAVVTe6CoGDUqRIqeaDwjLHjjLmD7kD0BAjwmbCY3n5Xyz2DgIf2TcjS08FNiy1JTL4CP2ynSQel6YkOEXauZrSW3ytMYGEAN4E/u0tR83537RVWs6W5p7BU8Fsl+p7zVdEClfahgLjjidVVApVi5u/YXydHVyTDfQpc9XqA4oQt2hhC3uLwiFnbOZRp2spDrtcTvC5A4/kXdc1YJ7Rxpi7Swxwyt1S5UWOQcDQHyfVE5XeVn9Il6ucv7syQuYe4aqrlYO6OVW3w0j77bhvZxJpMoM+zvQKBgQDv3URjw/bxVoVlHZ/58VUyv8R0OgQ0ZLcShktoJHEMe7ggD9gfit3LkoNrY7eH4LLyZNS7C5GKJ/pqtSeRnovqKQeSSft+OxCzIyXsIzJCz53yteghcdt4e0hjd3tcH8AiKwqLB3Wjv2CdUuwLd4djqlWcmBdMdvoH/ALgxwxFpwKBgQCaYfRMCZZrSjQQxB+O0NY1bivN24q5lxxz5KPBycZS/saZaziiM7KCwcmCY1yB59mjzu0BeTFhYOy6gSt+O0blpmg4IgSdRG1k8eDXvXtgHHbC0zH5d/UR5cn6PcxbOI+86ieNCYa9wGrlDQRjYa6urs76fn03+xVP3t1kZDjwZwKBgGiRww3nUdHW0WLKroKNdoIgXin5XPnmanV1/IvTT0GM8jFwFt1xcc4c+pQnrcxb5keMM72zhmh/k0lP3oc6Ym7cIkPhYvWeFGK0UQUINxIvZwF30lI6S97TiDRs02fPI7kBoKAJyXxwo1MS4nsBShHmIVqaZ5XbTJeMg0ixHiWDAoGAJAXPNx7VlltOIstggbaBBR6b4gDkMcHsxa4H9+PY/uyr8ohuQorFkHUfS+lbYIR06CAUdU+OEibHlg0l1OKH/HYDw3VMllWtIOy/hheUfiymGXemJYu0B2US5+0bjf14rKAGcoZShlwrlR6gc4ALfn8TlKeHGFTh+C0Mg6xPDOkCgYEA6zuA5tCxp+/4vH6XZ+HX1FVCQClZqJo4Xd4NXrHaLPSc2D7x5vV31BqTRXDyhugzVLJs6lBsR+n42HCZCKcIKebNSmpAktgA4P0b8pk8YAqU9abv2PMdDwe//jV7aXI1m1pFnkMOV5qoB27bgdq1tQRd1INg8EnVfEU6taE0Xj8=
  key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiMD4FvmHpaJFAYYb83fUY0kIZSWqARP9rKIYgkbQ7PYF5VsrmTwd8TftQxOVrz+YjR+md7neDmPCDsMNXVGQLXd5mUqVF5UC6+jVuNI3f8abJfG3FZd8BteKdOnCLoZj+D7ZZv6DFFNKAvCeXbXqhCuKpXA/+FdndLEGqcGWST/+dJJ8UxVACK3LOz6/HAIncMv1uoU7fpgqOpzMnVkAB9VGJqaTvG4QK6jy453/j0Z05HpR9MJGx2cfcLNmX5mQHEngmbPxk4ny51RthMkodAoFIKhfQFkZvNx9IJvsy8UveNT58wrNBv3fxsAXgiakNEYH//QtLRf6+D+hwFMI5QIDAQAB
  notify-url: http://www.ahzx.site/api/alipay/notify